### ISSUE TITLE
Exception during `npm install`

### ISSUE THREAD

**Issue by Flaise** [ilkosta/static-jade-brunch#18]
Gives a stack trace during installation and no .js files are generated. Using the plugin with Brunch doesn't work because, although npm doesn't think there's a problem, there's nothing to execute unless the compilation step works correctly.

    $ npm install static-jade-brunch
    npm WARN engine static-jade-brunch@1.7.0: wanted: {"node":"~0.6.10 || 0.8 || 0.9"} (current: {"node":"0.12.7","npm":"2.13.1"})
    /
    > static-jade-brunch@1.7.0 postinstall .../node_modules/static-jade-brunch
    > node setup.js postinstall

    Executing node node_modules/coffee-script/bin/coffee -o lib/ src/
    TypeError: undefined is not a function
        at writeJs (.../node_modules/static-jade-brunch/node_modules/coffee-script/lib/coffee-script/command.js:413:17)
        at compileScript (.../node_modules/static-jade-brunch/node_modules/coffee-script/lib/coffee-script/command.js:185:18)
        at .../node_modules/static-jade-brunch/node_modules/coffee-script/lib/coffee-script/command.js:150:18
        at fs.js:334:14
        at FSReqWrap.oncomplete (fs.js:95:15)
    static-jade-brunch@1.7.0 node_modules/static-jade-brunch
    ├── growl@1.6.1
    ├── ansi-color@0.2.1
    ├── coffee-script@1.3.3
    └── mkdirp@0.5.1 (minimist@0.0.8)

I'm using Ubuntu 14.04.

**Comment by Flaise** [comment]
I tested the HEAD revision of this repository and it appears to work without issue. Why haven't you done an `npm publish` yet?

**Comment by schulzch** [comment]
+1 for `npm publish`

**Comment by alxndrkalinin** [comment]
+1

**Comment by daimonion** [comment]
How much +1 do we need ?

**Comment by ilkosta** [comment]
you are right and soon I will update the package, but as I asked on https://github.com/ilkosta/static-jade-brunch/pull/17, I'm looking to someone that would like to maintain the project.

I'm no longer using brunch, CoffeeScript and increasingly rarely javascript.
I wish that those who find the project useful can freely contribute to its development.

In case you want to think about it let me know.
